# Generated by Django 6.0 on 2025-12-24 07:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("items", "0001_initial"),
        ("users", "0002_remove_user_password_hash"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this booking",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("declined", "Declined"),
                            ("closed", "Closed"),
                        ],
                        default="pending",
                        help_text="Current status of the booking (pending, accepted, active, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "deposit_status",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("received", "Received"),
                            ("returned", "Returned"),
                            ("kept", "Kept"),
                        ],
                        default="none",
                        help_text="Status of the security deposit (none, received, returned, kept)",
                        max_length=20,
                    ),
                ),
                (
                    "booking_code",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable booking reference code (e.g., SF-ABC123)",
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(help_text="When the borrowing period starts"),
                ),
                (
                    "return_by_date",
                    models.DateField(help_text="When the item should be returned by"),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total rental cost in DA (Algerian Dinar)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this booking was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this booking was last updated"
                    ),
                ),
                (
                    "borrower",
                    models.ForeignKey(
                        db_column="borrower_id",
                        help_text="The user who is borrowing the item",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings_as_borrower",
                        to="users.user",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        db_column="item_id",
                        help_text="The item being borrowed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="items.item",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        db_column="owner_id",
                        help_text="The user who owns the item",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings_as_owner",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking",
                "verbose_name_plural": "Bookings",
                "db_table": "bookings",
                "ordering": ["-created_at"],
            },
        ),
    ]
