# Generated by Django 5.2.5 on 2025-12-28 10:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("items", "0001_initial"),
        ("users", "0002_remove_user_password_hash"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("declined", "Declined"),
                            ("closed", "Closed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "deposit_status",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("received", "Received"),
                            ("returned", "Returned"),
                            ("kept", "Kept"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "booking_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("start_date", models.DateTimeField()),
                ("return_by_date", models.DateTimeField()),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "borrower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings_as_borrower",
                        to="users.user",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="items.item",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings_as_owner",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "bookings",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["owner", "-created_at"],
                        name="bookings_owner_i_ac7e88_idx",
                    ),
                    models.Index(
                        fields=["borrower", "-created_at"],
                        name="bookings_borrowe_b6c900_idx",
                    ),
                    models.Index(fields=["status"], name="bookings_status_51373b_idx"),
                ],
            },
        ),
    ]
