# Generated by Django 5.2.5 on 2026-01-08 22:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("booking_created", "Booking Request Created"),
                            ("booking_accepted", "Booking Request Accepted"),
                            ("booking_declined", "Booking Request Declined"),
                            ("item_returned", "Item Returned"),
                            ("deposit_released", "Deposit Released"),
                            ("rating_received", "Rating Received"),
                            ("booking_reminder", "Booking Reminder"),
                            ("chat_message", "New Chat Message"),
                        ],
                        db_index=True,
                        help_text="Type of notification event",
                        max_length=50,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Notification title (localized)", max_length=255
                    ),
                ),
                (
                    "body",
                    models.TextField(help_text="Notification body text (localized)"),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata (booking_id, item_id, etc.)",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether user has read this notification",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When notification was marked as read",
                        null=True,
                    ),
                ),
                (
                    "push_sent",
                    models.BooleanField(
                        default=False, help_text="Whether push notification was sent"
                    ),
                ),
                (
                    "push_sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When push notification was sent",
                        null=True,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Key to prevent duplicate notifications",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Soft delete timestamp", null=True
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="User who receives this notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="notificatio_recipie_2d3764_idx",
                    ),
                    models.Index(
                        fields=["recipient", "is_read", "-created_at"],
                        name="notificatio_recipie_dde14f_idx",
                    ),
                    models.Index(
                        fields=["notification_type", "-created_at"],
                        name="notificatio_notific_498289_idx",
                    ),
                    models.Index(
                        fields=["idempotency_key"], name="notif_idempotency_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("idempotency_key__isnull", False)),
                        fields=("idempotency_key",),
                        name="unique_idempotency_key",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fcm_token",
                    models.CharField(
                        help_text="Firebase Cloud Messaging token",
                        max_length=500,
                        unique=True,
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("android", "Android"),
                            ("ios", "iOS"),
                            ("web", "Web"),
                        ],
                        help_text="Platform type",
                        max_length=20,
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True, help_text="Device name/model", max_length=255
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether device is active for notifications",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last time this token was used/refreshed",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this device",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_devices",
                "ordering": ["-last_used_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="user_device_user_id_14e9e9_idx",
                    ),
                    models.Index(
                        fields=["fcm_token"], name="user_device_fcm_tok_657184_idx"
                    ),
                ],
            },
        ),
    ]
