# Generated by Django 5.2.5 on 2026-01-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("booking_created", "Booking Request Created"),
                    ("booking_canceled", "Booking Request Canceled"),
                    ("booking_accepted", "Booking Request Accepted"),
                    ("booking_declined", "Booking Request Declined"),
                    ("booking_expired", "Booking Request Expired"),
                    ("item_unavailable", "Item Marked Unavailable"),
                    ("item_deleted", "Item Deleted"),
                    ("booking_started", "Borrowing Started"),
                    ("booking_completed", "Borrowing Completed"),
                    ("booking_overdue", "Borrowing Overdue"),
                    ("dispute_opened", "Dispute Opened"),
                    ("dispute_resolved", "Dispute Resolved"),
                    ("item_returned", "Item Returned"),
                    ("rating_received", "Rating Received"),
                    ("rating_modified", "Rating Modified"),
                    ("report_submitted", "Report Submitted"),
                    ("report_reviewed", "Report Under Review"),
                    ("report_resolved", "Report Resolved"),
                    ("warning_issued", "Warning Issued"),
                    ("restriction_applied", "Restriction Applied"),
                    ("restriction_lifted", "Restriction Lifted"),
                    ("deposit_required", "Deposit Required"),
                    ("deposit_paid", "Deposit Paid"),
                    ("deposit_held", "Deposit Held"),
                    ("deposit_released", "Deposit Released"),
                    ("deposit_partial_refund", "Partial Deposit Refund"),
                    ("payment_failure", "Payment Failed"),
                    ("payment_success", "Payment Successful"),
                    ("account_verified", "Account Verified"),
                    ("password_changed", "Password Changed"),
                    ("new_login", "New Login Detected"),
                    ("account_suspended", "Account Suspended"),
                    ("account_reactivated", "Account Reactivated"),
                    ("terms_update", "Terms & Conditions Updated"),
                    ("system_announcement", "System Announcement"),
                    ("booking_reminder", "Booking Reminder"),
                ],
                db_index=True,
                help_text="Type of notification event",
                max_length=50,
            ),
        ),
    ]
