"""
Initial migration for notifications app.
Creates Notification and UserDevice models.
"""
# This file will be generated by Django when you run:
# python manage.py makemigrations notifications

# The migration will include:
# - Notification model with all fields and indexes
# - UserDevice model with all fields and indexes
# - Foreign key relationships to User model
# - Unique constraints for idempotency_key and fcm_token
