// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgztO1qIGQ-wtmmiqE6LFPGmGznp3bULg',
    appId: '1:446379664290:web:4d63128f65ae1bdb3cc8fb',
    messagingSenderId: '446379664290',
    projectId: 'sellefli',
    authDomain: 'sellefli.firebaseapp.com',
    storageBucket: 'sellefli.firebasestorage.app',
    measurementId: 'G-PWD4YDYWF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVnp_-XUq_JTqN0fNoVFD2DLHyfqsb4xo',
    appId: '1:446379664290:android:e42b5cf29ca4786e3cc8fb',
    messagingSenderId: '446379664290',
    projectId: 'sellefli',
    storageBucket: 'sellefli.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN0oFv1ixfjvkSR9b2EfIt0wj585rbdbI',
    appId: '1:446379664290:ios:84c941e2d15a6eaa3cc8fb',
    messagingSenderId: '446379664290',
    projectId: 'sellefli',
    storageBucket: 'sellefli.firebasestorage.app',
    iosBundleId: 'com.example.sellefli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN0oFv1ixfjvkSR9b2EfIt0wj585rbdbI',
    appId: '1:446379664290:ios:84c941e2d15a6eaa3cc8fb',
    messagingSenderId: '446379664290',
    projectId: 'sellefli',
    storageBucket: 'sellefli.firebasestorage.app',
    iosBundleId: 'com.example.sellefli',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgztO1qIGQ-wtmmiqE6LFPGmGznp3bULg',
    appId: '1:446379664290:web:6c3b3d6803f8d4193cc8fb',
    messagingSenderId: '446379664290',
    projectId: 'sellefli',
    authDomain: 'sellefli.firebaseapp.com',
    storageBucket: 'sellefli.firebasestorage.app',
    measurementId: 'G-MHBEXF59GJ',
  );
}
