# Generated by Django 6.0 on 2025-12-24 07:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        ("users", "0002_remove_user_password_hash"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("stars", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        db_column="booking_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="bookings.booking",
                    ),
                ),
                (
                    "rater_user",
                    models.ForeignKey(
                        db_column="rater_user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings_given",
                        to="users.user",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        db_column="target_user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings_received",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "ratings",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("booking", "rater_user"),
                        name="uniq_rating_booking_rater",
                    )
                ],
            },
        ),
    ]
