# Generated by Django 6.0 on 2025-12-29 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.RenameIndex(
        #     model_name="rating",
        #     new_name="ratings_rater_u_ec6d4f_idx",
        #     old_name="ratings_rater_i_f01f0f_idx",
        # ),
        # migrations.RemoveField(
        #     model_name="rating",
        #     name="updated_at",
        # ),
        # migrations.AlterField(
        #     model_name="rating",
        #     name="rater",
        #     field=models.ForeignKey(
        #         db_column="rater_user_id",
        #         on_delete=django.db.models.deletion.CASCADE,
        #         related_name="ratings_given",
        #         to=settings.AUTH_USER_MODEL,
        #     ),
        # ),
        # migrations.AlterField(
        #     model_name="rating",
        #     name="target_user",
        #     field=models.ForeignKey(
        #         db_column="target_user_id",
        #         on_delete=django.db.models.deletion.CASCADE,
        #         related_name="ratings_received",
        #         to=settings.AUTH_USER_MODEL,
        #     ),
        # ),
    ]
