# Generated by Django 6.0 on 2025-12-24 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("item_images", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemimage",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="itemimage",
            name="updated_at",
        ),
    ]
