# Generated by Django 5.2.5 on 2025-12-28 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("item_images", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemimage",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="itemimage",
            name="updated_at",
        ),
    ]
